export const DataCoupons = [
  {
    id: 9,
    category: "Food",
    title: "Zion sabich",
    description: "updated",
    startDate: new Date("2022-07-08"),
    endDate: new Date("2022-07-13"),
    amount: 22,
    price: 20.0,
    image: "zion.png",
  },
  {
    id: 10,
    category: "Beverages",
    title: "Zion sabich drink",
    description: "Cold drink",
    startDate: new Date("2022-07-08"),
    endDate: new Date("2022-07-13"),
    amount: 23,
    price: 200.0,
    image: "zion.png",
  },
  {
    id: 11,
    category: "Desserts",
    title: "Zion sabich desert",
    description: "Bavaria",
    startDate: new Date("2022-07-08"),
    endDate: new Date("2022-07-13"),
    amount: 23,
    price: 8.0,
    image: "zion.png",
  },
];